(function(){
var CATS=[{"en": "Food & Hospitality", "fr": "Restauration et hospitalité", "items": [{"id": "restaurants", "en": "Restaurants", "fr": "Restaurants", "icon": "🍽️", "price": "197"}]}, {"en": "Legal", "fr": "Juridique", "items": [{"id": "personal-injury-law", "en": "Personal injury law", "fr": "Droit des blessures corporelles", "icon": "⚖️", "price": "197"}, {"id": "family-law", "en": "Family & divorce law", "fr": "Droit de la famille et divorce", "icon": "👪", "price": "197"}, {"id": "immigration-law", "en": "Immigration law", "fr": "Droit de l'immigration", "icon": "🛂", "price": "197"}]}, {"en": "Health & Wellness", "fr": "Santé et bien-être", "items": [{"id": "cosmetic-plastic-surgery", "en": "Cosmetic & plastic surgery", "fr": "Chirurgie esthétique et plastique", "icon": "✨", "price": "197"}, {"id": "med-spas", "en": "Med spas & aesthetics", "fr": "Med spas et soins esthétiques", "icon": "💉", "price": "197"}, {"id": "cosmetic-dentistry", "en": "Cosmetic & implant dentistry", "fr": "Dentisterie esthétique et implantologie", "icon": "🦷", "price": "197"}, {"id": "weight-loss-glp1", "en": "Weight-loss & GLP-1 clinics", "fr": "Cliniques de perte de poids et GLP-1", "icon": "📉", "price": "197"}, {"id": "fertility-ivf", "en": "Fertility & IVF", "fr": "Fertilité et FIV", "icon": "🍼", "price": "197"}, {"id": "hair-restoration", "en": "Hair restoration", "fr": "Restauration capillaire", "icon": "💈", "price": "197"}, {"id": "dermatology", "en": "Dermatology", "fr": "Dermatologie", "icon": "🧴", "price": "197"}, {"id": "mens-health-trt", "en": "Men's health & TRT", "fr": "Santé masculine et hormonothérapie (TRT)", "icon": "💪", "price": "197"}, {"id": "lasik-vision", "en": "LASIK & vision surgery", "fr": "LASIK et chirurgie de la vision", "icon": "👁️", "price": "197"}, {"id": "chiropractors", "en": "Chiropractors", "fr": "Chiropraticiens", "icon": "🦴", "price": "197"}, {"id": "veterinary", "en": "Veterinary clinics", "fr": "Cliniques vétérinaires", "icon": "🐾", "price": "197"}]}, {"en": "Home, Trades & Property", "fr": "Maison, métiers et propriété", "items": [{"id": "hvac-plumbing-electrical", "en": "HVAC, plumbing & electrical", "fr": "CVC, plomberie et electricite", "icon": "🔧", "price": "197"}, {"id": "roofing", "en": "Roofing & exteriors", "fr": "Toiture et revêtements extérieurs", "icon": "🏠", "price": "197"}, {"id": "solar", "en": "Solar installers", "fr": "Installateurs de panneaux solaires", "icon": "☀️", "price": "197"}, {"id": "custom-builders", "en": "Custom builders & remodelers", "fr": "Constructeurs sur mesure et rénovateurs", "icon": "🏗️", "price": "197"}, {"id": "real-estate", "en": "Real estate teams", "fr": "Équipes immobilières", "icon": "🏡", "price": "197"}, {"id": "mortgage-brokers", "en": "Mortgage brokers", "fr": "Courtiers hypothécaires", "icon": "🏦", "price": "197"}]}];
var T={en:{ey:'Every local industry',h:'Restaurants are just the start.',sub:'We run this exact SEO + AI-visibility engine for these industries too. Pick yours to see the tailored version.'},fr:{ey:'Toutes les industries locales',h:'Les restaurants ne sont qu\'un début.',sub:'On fait rouler ce même moteur SEO + visibilité IA pour ces industries aussi. Choisissez la vôtre pour voir la version sur mesure.'}};
function gl(){try{return localStorage.getItem('vanta_lang')||'en';}catch(e){return 'en';}}
function render(lang){var host=document.getElementById('outreachNiches');if(!host)return;lang=lang||gl();
 var cats=CATS.map(function(c){var cards=c.items.map(function(n){return '<a class="onp-card" href="/#/i/'+n.id+'"><div class="onp-top"><span class="onp-ic">'+n.icon+'</span><span class="onp-go">&#8594;</span></div><div class="onp-nm">'+(lang==='fr'?n.fr:n.en)+'</div><div class="onp-pr">'+(lang==='fr'?('dès '+n.price+' $/mois'):('from $'+n.price+'/mo'))+'</div></a>';}).join('');return '<div class="onp-cat"><div class="onp-ch">'+(lang==='fr'?c.fr:c.en)+'</div><div class="onp-grid">'+cards+'</div></div>';}).join('');
 host.innerHTML='<div class="eyebrow" style="text-align:center">'+T[lang].ey+'</div><h2 style="text-align:center;margin:10px 0 8px">'+T[lang].h+'</h2><p style="text-align:center;color:var(--mut);max-width:660px;margin:0 auto 26px;font-size:15.5px">'+T[lang].sub+'</p>'+cats;}
window.__renderOutreachNiches=render;
var st=document.createElement('style');st.textContent=".onp{padding:clamp(50px,8vw,90px) 0}.onp-cat{margin-top:32px}.onp-ch{font-size:12px;letter-spacing:.2em;text-transform:uppercase;color:var(--lilac2);font-weight:700;margin-bottom:14px}.onp-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(238px,1fr));gap:15px}.onp-card{display:block;background:linear-gradient(180deg,rgba(21,14,42,.55),rgba(7,6,13,.35));border:1px solid var(--line);border-radius:16px;padding:17px;transition:.16s;text-decoration:none}.onp-card:hover{transform:translateY(-2px);border-color:var(--line2);box-shadow:0 18px 44px -22px rgba(124,58,237,.8)}.onp-top{display:flex;justify-content:space-between;align-items:center}.onp-ic{font-size:26px}.onp-go{color:var(--mut2);font-size:16px}.onp-nm{font-weight:700;font-size:16px;color:var(--white);margin-top:13px}.onp-pr{font-size:13px;color:var(--mut);margin-top:4px}";document.head.appendChild(st);
render();
})();
